version: '3.8'

services:

  web:
    container_name: maven-backend
    build: .
    environment:
      - NODE_ENV=development
      - PORT=9000
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - 9000:9000
    depends_on:
      - postgres

  postgres:
    container_name: maven-db
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
