export const countriesRawData = [
    {
        name: 'Afghanistan',
        iso2: 'AF',
        iso3: 'AFG',
        capital: 'Kabul',
        region: 'AS',
        currency: {
            code: 'AFN',
            name: 'Afghan afghani',
            symbol: '؋',
        },
        language: {
            code: 'ps',
            name: 'Pashto',
        },
        flag: '',
        numCode: '+93',
        isoCode: '004',
    },
    {
        name: 'Albania',
        iso2: 'AL',
        iso3: 'ALB',
        capital: 'Tirana',
        region: 'EU',
        currency: {
            code: 'ALL',
            name: 'Albanian lek',
            symbol: 'L',
        },
        language: {
            code: 'sq',
            name: 'Albanian',
        },
        flag: '',
        numCode: '+355',
        isoCode: '008',
    },
    {
        name: 'Algeria',
        code: 'DZ',
        iso2: 'DZ',
        iso3: 'DZA',
        capital: 'Algiers',
        region: 'AF',
        currency: {
            code: 'DZD',
            name: 'Algerian dinar',
            symbol: 'د.ج',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+213',
        isoCode: '012',
    },
    {
        name: 'American Samoa',
        iso2: 'AS',
        iso3: 'ASM',
        capital: 'Pago Pago',
        region: 'OC',
        currency: {
            code: 'USD',
            name: 'United State Dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '016',
    },
    {
        name: 'Andorra',
        iso2: 'AN',
        iso3: 'AND',
        capital: 'Andorra la Vella',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'ca',
            name: 'Catalan',
        },
        flag: '',
        numCode: '+376',
        isoCode: '020',
    },
    {
        name: 'Angola',
        iso2: 'AO',
        iso3: 'AGO',
        capital: 'Luanda',
        region: 'AF',
        currency: {
            code: 'AOA',
            name: 'Angolan kwanza',
            symbol: 'Kz',
        },
        language: {
            code: 'pt',
            name: 'Portuguese',
        },
        flag: '',
        numCode: '+244',
        isoCode: '024',
    },
    {
        name: 'Anguilla',
        iso2: 'AI',
        iso3: 'AIA',
        capital: 'The Valley',
        region: 'NA',
        currency: {
            code: 'XCD',
            name: 'East Caribbean dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+43',
        isoCode: '660',
    },
    {
        name: 'Antigua and Barbuda',
        iso2: 'AG',
        iso3: 'ATG',
        capital: "Saint John's",
        region: 'NA',
        currency: {
            code: 'XCD',
            name: 'East Caribbean dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '028',
    },
    {
        name: 'Argentina',
        iso2: 'AR',
        iso3: 'ARG',
        capital: 'Buenos Aires',
        region: 'SA',
        currency: {
            code: 'ARS',
            name: 'Argentine peso',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+54',
        isoCode: '032',
    },
    {
        name: 'Armenia',
        iso2: 'AM',
        iso3: 'AMR',
        capital: 'Yerevan',
        region: 'AS',
        currency: {
            code: 'AMD',
            name: 'Armenian dram',
            symbol: null,
        },
        language: {
            code: 'hy',
            name: 'Armenian',
        },
        flag: '',
        numCode: '+374',
        isoCode: '051',
    },
    {
        name: 'Aruba',
        iso2: 'AW',
        iso3: 'ABW',
        capital: 'Oranjestad',
        region: 'SA',
        currency: {
            code: 'AWG',
            name: 'Aruban florin',
            symbol: 'ƒ',
        },
        language: {
            code: 'nl',
            name: 'Dutch',
        },
        flag: '',
        numCode: '+297',
        isoCode: '533',
    },
    {
        name: 'Australia',
        iso2: 'AU',
        iso3: 'AUS',
        capital: 'Canberra',
        region: 'OC',
        currency: {
            code: 'AUD',
            name: 'Australian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+61',
        isoCode: '036',
    },
    {
        name: 'Azerbaijan',
        iso2: 'AZ',
        iso3: 'AZE',
        capital: 'Baku',
        region: 'AS',
        currency: {
            code: 'AZN',
            name: 'Azerbaijani manat',
            symbol: null,
        },
        language: {
            code: 'az',
            name: 'Azerbaijani',
        },
        flag: '',
        numCode: '+994',
        isoCode: '031',
    },
    {
        name: 'Bahamas',
        iso2: 'BS',
        iso3: 'BHS',
        capital: 'Nassau',
        region: 'NA',
        currency: {
            code: 'BSD',
            name: 'Bahamian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '044',
    },
    {
        name: 'Bahrain',
        iso2: 'BH',
        iso3: 'BHR',
        capital: 'Manama',
        region: 'AS',
        currency: {
            code: 'BHD',
            name: 'Bahraini dinar',
            symbol: '.د.ب',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+973',
        isoCode: '048',
    },
    {
        name: 'Bangladesh',
        iso2: 'BD',
        iso3: 'BGD',
        capital: 'Dhaka',
        region: 'AS',
        currency: {
            code: 'BDT',
            name: 'Bangladeshi taka',
            symbol: '৳',
        },
        language: {
            code: 'bn',
            name: 'Bengali',
        },
        flag: '',
        numCode: '+880',
        isoCode: '050',
    },
    {
        name: 'Barbados',
        iso2: 'BB',
        iso3: 'BRB',
        capital: 'Bridgetown',
        region: 'NA',
        currency: {
            code: 'BBD',
            name: 'Barbadian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '052',
    },
    {
        name: 'Belarus',
        iso2: 'BY',
        iso3: 'BLR',
        capital: 'Minsk',
        region: 'EU',
        currency: {
            code: 'BYN',
            name: 'New Belarusian ruble',
            symbol: 'Br',
        },
        language: {
            code: 'be',
            name: 'Belarusian',
        },
        flag: '',
        numCode: '+375',
        isoCode: '112',
    },
    {
        name: 'Belgium',
        iso2: 'BE',
        iso3: 'BEL',
        capital: 'Brussels',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'nl',
            name: 'Dutch',
        },
        flag: '',
        numCode: '+32',
        isoCode: '056',
    },
    {
        name: 'Belize',
        iso2: 'BZ',
        iso3: 'BLZ',
        capital: 'Belmopan',
        region: 'NA',
        currency: {
            code: 'BZD',
            name: 'Belize dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+501',
        isoCode: '084',
    },
    {
        name: 'Benin',
        iso2: 'BJ',
        iso3: 'BEN',
        capital: 'Porto-Novo',
        region: 'AF',
        currency: {
            code: 'XOF',
            name: 'West African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+229',
        isoCode: '204',
    },
    {
        name: 'Bermuda',
        iso2: 'BM',
        iso3: 'BMU',
        capital: 'Hamilton',
        region: 'NA',
        currency: {
            code: 'BMD',
            name: 'Bermudian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '060',
    },
    {
        name: 'Bhutan',
        iso2: 'BT',
        iso3: 'BTN',
        capital: 'Thimphu',
        region: 'AS',
        currency: {
            code: 'BTN',
            name: 'Bhutanese ngultrum',
            symbol: 'Nu.',
        },
        language: {
            code: 'dz',
            name: 'Dzongkha',
        },
        flag: '',
        numCode: '+975',
        isoCode: '064',
    },
    {
        name: 'Bolivia (Plurinational State of)',
        iso2: 'BO',
        iso3: 'BOL',
        capital: 'Sucre',
        region: 'SA',
        currency: {
            code: 'BOB',
            name: 'Bolivian boliviano',
            symbol: 'Bs.',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+591',
        isoCode: '068',
    },
    {
        name: 'Bosnia and Herzegovina',
        iso2: 'BA',
        iso3: 'BIH',
        capital: 'Sarajevo',
        region: 'EU',
        currency: {
            code: 'BAM',
            name: 'Bosnia and Herzegovina convertible mark',
            symbol: null,
        },
        language: {
            code: 'bs',
            name: 'Bosnian',
        },
        flag: '',
        numCode: '+387',
        isoCode: '070',
    },
    {
        name: 'Botswana',
        iso2: 'BW',
        iso3: 'BWA',
        capital: 'Gaborone',
        region: 'AF',
        currency: {
            code: 'BWP',
            name: 'Botswana pula',
            symbol: 'P',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+267',
        isoCode: '072',
    },
    {
        name: 'Brazil',
        iso2: 'BR',
        iso3: 'BRA',
        capital: 'Brasília',
        region: 'SA',
        currency: {
            code: 'BRL',
            name: 'Brazilian real',
            symbol: 'R$',
        },
        language: {
            code: 'pt',
            name: 'Portuguese',
        },
        flag: '',
        numCode: '+55',
        isoCode: '076',
    },
    {
        name: 'British Indian Ocean Territory',
        iso2: 'IO',
        iso3: 'IOA',
        capital: 'Diego Garcia',
        region: 'AF',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+246',
        isoCode: '086',
    },
    {
        name: 'Virgin Islands (British)',
        iso2: 'VG',
        capital: 'Road Town',
        region: 'NA',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '092',
    },
    {
        name: 'Virgin Islands (U.S.)',
        iso2: 'VI',
        iso3: 'VI',
        capital: 'Charlotte Amalie',
        region: 'NA',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '850',
    },
    {
        name: 'Brunei Darussalam',
        iso2: 'BN',
        iso3: 'BRN',
        capital: 'Bandar Seri Begawan',
        region: 'AS',
        currency: {
            code: 'BND',
            name: 'Brunei dollar',
            symbol: '$',
        },
        language: {
            code: 'ms',
            name: 'Malay',
        },
        flag: '',
        numCode: '+673',
        isoCode: '096',
    },
    {
        name: 'Bulgaria',
        iso2: 'Bg',
        iso3: 'BgR',
        capital: 'Sofia',
        region: 'EU',
        currency: {
            code: 'BGN',
            name: 'Bulgarian lev',
            symbol: 'лв',
        },
        language: {
            code: 'bg',
            name: 'Bulgarian',
        },
        flag: '',
        numCode: '+359',
        isoCode: '100',
    },
    {
        name: 'Burkina Faso',
        iso2: 'Bf',
        iso3: 'BFA',
        capital: 'Ouagadougou',
        region: 'AF',
        currency: {
            code: 'XOF',
            name: 'West African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+226',
        isoCode: '854',
    },
    {
        name: 'Burundi',
        iso2: 'BI',
        iso3: 'BDI',
        capital: 'Bujumbura',
        region: 'AF',
        currency: {
            code: 'BIF',
            name: 'Burundian franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+257',
        isoCode: '108',
    },
    {
        name: 'Cambodia',
        iso2: 'KH',
        iso3: 'KHM',
        capital: 'Phnom Penh',
        region: 'AS',
        currency: {
            code: 'KHR',
            name: 'Cambodian riel',
            symbol: '៛',
        },
        language: {
            code: 'km',
            name: 'Khmer',
        },
        flag: '',
        numCode: '+855',
        isoCode: '116',
    },
    {
        name: 'Cameroon',
        iso2: 'CM',
        iso3: 'CMR',
        capital: 'Yaoundé',
        region: 'AF',
        currency: {
            code: 'XAF',
            name: 'Central African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+237',
        isoCode: '120',
    },
    {
        name: 'Canada',
        iso2: 'CA',
        iso3: 'CAN',
        capital: 'Ottawa',
        region: 'NA',
        currency: {
            code: 'CAD',
            name: 'Canadian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '124',
    },
    {
        name: 'Cabo Verde',
        iso2: 'CV',
        iso3: 'CV',
        capital: 'Praia',
        region: 'AF',
        currency: {
            code: 'CVE',
            name: 'Cape Verdean escudo',
            symbol: 'Esc',
        },
        language: {
            code: 'pt',
            name: 'Portuguese',
        },
        flag: '',
        numCode: '+238',
        isoCode: '132',
    },
    {
        name: 'Cayman Islands',
        iso2: 'KY',
        iso3: 'CYM',
        capital: 'George Town',
        region: 'NA',
        demonym: 'Caymanian',
        currency: {
            code: 'KYD',
            name: 'Cayman Islands dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '136',
    },
    {
        name: 'Central African Republic',
        iso2: 'CF',
        iso3: 'CAF',
        capital: 'Bangui',
        region: 'AF',
        currency: {
            code: 'XAF',
            name: 'Central African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+236',
        isoCode: '140',
    },
    {
        name: 'Chile',
        iso2: 'CL',
        iso3: 'CHL',
        capital: 'Santiago',
        region: 'SA',
        currency: {
            code: 'CLP',
            name: 'Chilean peso',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+56',
        isoCode: '152',
    },
    {
        name: 'China',
        iso2: 'CN',
        iso3: 'CHN',
        capital: 'Beijing',
        region: 'AS',
        currency: {
            code: 'CNY',
            name: 'Chinese yuan',
            symbol: '¥',
        },
        language: {
            code: 'zh',
            name: 'Chinese',
        },
        flag: '',
        numCode: '+86',
        isoCode: '156',
    },
    {
        name: 'Colombia',
        iso2: 'CO',
        iso3: 'COL',
        capital: 'Bogotá',
        region: 'SA',
        currency: {
            code: 'COP',
            name: 'Colombian peso',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+57',
        isoCode: '170',
    },
    {
        name: 'Comoros',
        iso2: 'KM',
        iso3: 'COM',
        capital: 'Moroni',
        region: 'AF',
        currency: {
            code: 'KMF',
            name: 'Comorian franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+269',
        isoCode: '174',
    },
    {
        name: 'Congo',
        iso2: 'CG',
        iso3: 'COG',
        capital: 'Brazzaville',
        region: 'AF',
        currency: {
            code: 'XAF',
            name: 'Central African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+242',
        isoCode: '178',
    },
    {
        name: 'Congo (Democratic Republic of the)',
        iso2: 'CO',
        iso3: 'COD',
        capital: 'Kinshasa',
        region: 'AF',
        currency: {
            code: 'CDF',
            name: 'Congolese franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+243',
        isoCode: '180',
    },
    {
        name: 'Cook Islands',
        iso2: 'KK',
        iso3: 'COK',
        capital: 'Avarua',
        region: 'OC',
        currency: {
            code: 'NZD',
            name: 'New Zealand dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+682',
        isoCode: '184',
    },
    {
        name: 'Costa Rica',
        iso2: 'CR',
        iso3: 'CRI',
        capital: 'San José',
        region: 'NA',
        currency: {
            code: 'CRC',
            name: 'Costa Rican colón',
            symbol: '₡',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+506',
        isoCode: '188',
    },
    {
        name: 'Croatia',
        iso2: 'HR',
        iso3: 'HRV',
        capital: 'Zagreb',
        region: 'EU',
        currency: {
            code: 'HRK',
            name: 'Croatian kuna',
            symbol: 'kn',
        },
        language: {
            code: 'hr',
            name: 'Croatian',
        },
        flag: '',
        numCode: '+385',
        isoCode: '191',
    },
    {
        name: 'Cuba',
        iso2: 'CU',
        iso3: 'CUB',
        capital: 'Havana',
        region: 'NA',
        currency: {
            code: 'CUC',
            name: 'Cuban convertible peso',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+53',
        isoCode: '192',
    },
    {
        name: 'Cyprus',
        iso2: 'CY',
        iso3: 'CYP',
        capital: 'Nicosia',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'tr',
            name: 'Turkish',
        },
        flag: '',
        numCode: '+357',
        isoCode: '196',
    },
    {
        name: 'Czech Republic',
        iso2: 'CZ',
        iso3: 'CZE',
        capital: 'Prague',
        region: 'EU',
        currency: {
            code: 'CZK',
            name: 'Czech koruna',
            symbol: 'Kč',
        },
        language: {
            code: 'cs',
            name: 'Czech',
        },
        flag: '',
        numCode: '+420',
        isoCode: '203',
    },
    {
        name: 'Denmark',
        iso2: 'DK',
        iso3: 'DNK',
        capital: 'Copenhagen',
        region: 'EU',
        currency: {
            code: 'DKK',
            name: 'Danish krone',
            symbol: 'kr',
        },
        language: {
            code: 'da',
            name: 'Danish',
        },
        flag: '',
        numCode: '+45',
        isoCode: '208',
    },
    {
        name: 'Djibouti',
        iso2: 'DJ',
        iso3: 'DJI',
        capital: 'Djibouti',
        region: 'AF',
        currency: {
            code: 'DJF',
            name: 'Djiboutian franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+253',
        isoCode: '262',
    },
    {
        name: 'Dominica',
        iso2: 'DM',
        iso3: 'DMA',
        capital: 'Roseau',
        region: 'NA',
        currency: {
            code: 'XCD',
            name: 'East Caribbean dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '212',
    },
    {
        name: 'Dominican Republic',
        iso2: 'DO',
        iso3: 'DOM',
        capital: 'Santo Domingo',
        region: 'NA',
        currency: {
            code: 'DOP',
            name: 'Dominican peso',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+1',
        isoCode: '214',
    },
    {
        name: 'Ecuador',
        iso2: 'EC',
        iso3: 'ECU',
        capital: 'Quito',
        region: 'SA',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+593',
        isoCode: '218',
    },
    {
        name: 'Egypt',
        iso2: 'EG',
        iso3: 'EGY',
        capital: 'Cairo',
        region: 'AF',
        currency: {
            code: 'EGP',
            name: 'Egyptian pound',
            symbol: '£',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+20',
        isoCode: '818',
    },
    {
        name: 'El Salvador',
        iso2: 'SV',
        iso3: 'SLV',
        capital: 'San Salvador',
        region: 'NA',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+503',
        isoCode: '222',
    },
    {
        name: 'Equatorial Guinea',
        iso2: 'GQ',
        iso3: 'GNQ',
        capital: 'Malabo',
        region: 'AF',
        currency: {
            code: 'XAF',
            name: 'Central African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+240',
        isoCode: '226',
    },
    {
        name: 'Eritrea',
        iso2: 'ER',
        iso3: 'ERI',
        capital: 'Asmara',
        region: 'AF',
        currency: {
            code: 'ERN',
            name: 'Eritrean nakfa',
            symbol: 'Nfk',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+291',
        isoCode: '232',
    },
    {
        name: 'Estonia',
        iso2: 'EE',
        iso3: 'EST',
        capital: 'Tallinn',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'et',
            name: 'Estonian',
        },
        flag: '',
        numCode: '+372',
        isoCode: '233',
    },
    {
        name: 'Ethiopia',
        iso2: 'ET',
        iso3: 'ETH',
        capital: 'Addis Ababa',
        region: 'AF',
        currency: {
            code: 'ETB',
            name: 'Ethiopian birr',
            symbol: 'Br',
        },
        language: {
            code: 'am',
            name: 'Amharic',
        },
        flag: '',
        numCode: '+251',
        isoCode: '231',
    },
    {
        name: 'Falkland Islands (Malvinas)',
        iso2: 'FK',
        iso3: 'FLK',
        capital: 'Stanley',
        region: 'SA',
        currency: {
            code: 'FKP',
            name: 'Falkland Islands pound',
            symbol: '£',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+500',
        isoCode: '238',
    },
    {
        name: 'Faroe Islands',
        iso2: 'FO',
        iso3: 'FRO',
        capital: 'Tórshavn',
        region: 'EU',
        currency: {
            code: 'DKK',
            name: 'Danish krone',
            symbol: 'kr',
        },
        language: {
            code: 'fo',
            name: 'Faroese',
        },
        flag: '',
        numCode: '+298',
        isoCode: '234',
    },
    {
        name: 'Fiji',
        iso2: 'FJ',
        iso3: 'FJI',
        capital: 'Suva',
        region: 'OC',
        currency: {
            code: 'FJD',
            name: 'Fijian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+679',
        isoCode: '242',
    },
    {
        name: 'Finland',
        iso2: 'FI',
        iso3: 'FIN',
        capital: 'Helsinki',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fi',
            name: 'Finnish',
        },
        flag: '',
        numCode: '+358',
        isoCode: '246',
    },
    {
        name: 'France',
        iso2: 'FR',
        iso3: 'FRA',
        capital: 'Paris',
        region: 'EU',
        demonym: 'French',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+33',
        isoCode: '250',
    },
    {
        name: 'French Guiana',
        iso2: 'GF',
        iso3: 'GUF',
        capital: 'Cayenne',
        region: 'SA',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+594',
        isoCode: '254',
    },
    {
        name: 'French Polynesia',
        iso2: 'PF',
        iso3: 'PYF',
        capital: 'Papeetē',
        region: 'OC',
        currency: {
            code: 'XPF',
            name: 'CFP franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+689',
        isoCode: '258',
    },
    {
        name: 'Gabon',
        iso2: 'GA',
        iso3: 'GAB',
        capital: 'Libreville',
        region: 'AF',
        currency: {
            code: 'XAF',
            name: 'Central African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+241',
        isoCode: '266',
    },
    {
        name: 'Gambia',
        iso2: 'GM',
        iso3: 'GMB',
        capital: 'Banjul',
        region: 'AF',
        currency: {
            code: 'GMD',
            name: 'Gambian dalasi',
            symbol: 'D',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+220',
        isoCode: '270',
    },
    {
        name: 'Georgia',
        iso2: 'GE',
        iso3: 'GEO',
        capital: 'Tbilisi',
        region: 'AS',
        currency: {
            code: 'GEL',
            name: 'Georgian Lari',
            symbol: 'ლ',
        },
        language: {
            code: 'ka',
            name: 'Georgian',
        },
        flag: '',
        numCode: '+995',
        isoCode: '268',
    },
    {
        name: 'Germany',
        iso2: 'DE',
        iso3: 'DEU',
        capital: 'Berlin',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'de',
            name: 'German',
        },
        flag: '',
        numCode: '+49',
        isoCode: '276',
    },
    {
        name: 'Ghana',
        iso2: 'GH',
        iso3: 'GHA',
        capital: 'Accra',
        region: 'AF',
        currency: {
            code: 'GHS',
            name: 'Ghanaian cedi',
            symbol: '₵',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+233',
        isoCode: '288',
    },
    {
        name: 'Gibraltar',
        iso2: 'GI',
        iso3: 'GIB',
        capital: 'Gibraltar',
        region: 'EU',
        currency: {
            code: 'GIP',
            name: 'Gibraltar pound',
            symbol: '£',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+350',
        isoCode: '292',
    },
    {
        name: 'Greece',
        iso2: 'GR',
        iso3: 'GRC',
        capital: 'Athens',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'el',
            name: 'Greek (modern)',
        },
        flag: '',
        numCode: '+30',
        isoCode: '300',
    },
    {
        name: 'Greenland',
        iso2: 'GL',
        iso3: 'GRL',
        capital: 'Nuuk',
        region: 'NA',
        currency: {
            code: 'DKK',
            name: 'Danish krone',
            symbol: 'kr',
        },
        language: {
            code: 'kl',
            name: 'Kalaallisut',
        },
        flag: '',
        numCode: '+299',
        isoCode: '304',
    },
    {
        name: 'Grenada',
        iso2: 'GB',
        iso3: 'GRB',
        capital: "St. George's",
        region: 'NA',
        currency: {
            code: 'XCD',
            name: 'East Caribbean dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '308',
    },
    {
        name: 'Guadeloupe',
        iso2: 'GP',
        iso3: 'GLP',
        capital: 'Basse-Terre',
        region: 'NA',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+590',
        isoCode: '312',
    },
    {
        name: 'Guam',
        iso2: 'GU',
        iso3: 'GUM',
        capital: 'Hagåtña',
        region: 'OC',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '316',
    },
    {
        name: 'Guatemala',
        iso2: 'GT',
        iso3: 'GTM',
        capital: 'Guatemala City',
        region: 'NA',
        currency: {
            code: 'GTQ',
            name: 'Guatemalan quetzal',
            symbol: 'Q',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+502',
        isoCode: '320',
    },
    {
        name: 'Guinea',
        iso2: 'GN',
        iso3: 'GIN',
        capital: 'Conakry',
        region: 'AF',
        currency: {
            code: 'GNF',
            name: 'Guinean franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+224',
        isoCode: '324',
    },
    {
        name: 'Guinea-Bissau',
        iso2: 'GW',
        iso3: 'GNB',
        capital: 'Bissau',
        region: 'AF',
        currency: {
            code: 'XOF',
            name: 'West African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'pt',
            name: 'Portuguese',
        },
        flag: '',
        numCode: '+245',
        isoCode: '624',
    },
    {
        name: 'Guyana',
        iso2: 'GY',
        iso3: 'GUY',
        capital: 'Georgetown',
        region: 'SA',
        currency: {
            code: 'GYD',
            name: 'Guyanese dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+592',
        isoCode: '328',
    },
    {
        name: 'Haiti',
        iso2: 'HT',
        iso3: 'HTI',
        capital: 'Port-au-Prince',
        region: 'Americas',
        currency: {
            code: 'HTG',
            name: 'Haitian gourde',
            symbol: 'G',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+509',
        isoCode: '332',
    },
    {
        name: 'Holy See',
        iso2: 'VA',
        iso3: 'VAT',
        capital: 'Rome',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+39',
        isoCode: '336',
    },
    {
        name: 'Honduras',
        iso2: 'HN',
        iso3: 'HND',
        capital: 'Tegucigalpa',
        region: 'NA',
        currency: {
            code: 'HNL',
            name: 'Honduran lempira',
            symbol: 'L',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+504',
        isoCode: '340',
    },
    {
        name: 'Hong Kong',
        iso2: 'HK',
        iso3: 'HKG',
        capital: 'City of Victoria',
        region: 'AS',
        currency: {
            code: 'HKD',
            name: 'Hong Kong dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+852',
        isoCode: '344',
    },
    {
        name: 'Hungary',
        iso2: 'HU',
        iso3: 'HUN',
        capital: 'Budapest',
        region: 'EU',
        currency: {
            code: 'HUF',
            name: 'Hungarian forint',
            symbol: 'Ft',
        },
        language: {
            code: 'hu',
            name: 'Hungarian',
        },
        flag: '',
        numCode: '+36',
        isoCode: '348',
    },
    {
        name: 'Iceland',
        iso2: 'IS',
        iso3: 'ISL',
        capital: 'Reykjavík',
        region: 'EU',
        currency: {
            code: 'ISK',
            name: 'Icelandic króna',
            symbol: 'kr',
        },
        language: {
            code: 'is',
            name: 'Icelandic',
        },
        flag: '',
        numCode: '+354',
        isoCode: '352',
    },
    {
        name: 'India',
        iso2: 'IN',
        iso3: 'IND',
        capital: 'New Delhi',
        region: 'AS',
        currency: {
            code: 'INR',
            name: 'Indian rupee',
            symbol: '₹',
        },
        language: {
            code: 'hi',
            name: 'Hindi',
        },
        flag: '',
        numCode: '+91',
        isoCode: '356',
    },
    {
        name: 'Indonesia',
        iso2: 'ID',
        iso3: 'IDN',
        capital: 'Jakarta',
        region: 'AS',
        currency: {
            code: 'IDR',
            name: 'Indonesian rupiah',
            symbol: 'Rp',
        },
        language: {
            code: 'id',
            name: 'Indonesian',
        },
        flag: '',
        numCode: '+62',
        isoCode: '360',
    },
    {
        name: "Côte d'Ivoire",
        iso2: 'CI',
        iso3: 'CI',
        capital: 'Yamoussoukro',
        region: 'AF',
        currency: {
            code: 'XOF',
            name: 'West African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+225',
        isoCode: '384',
    },
    {
        name: 'Iran (Islamic Republic of)',
        iso2: 'IR',
        iso3: 'IRN',
        capital: 'Tehran',
        region: 'AS',
        currency: {
            code: 'IRR',
            name: 'Iranian rial',
            symbol: '﷼',
        },
        language: {
            code: 'fa',
            name: 'Persian (Farsi)',
        },
        flag: '',
        numCode: '+98',
        isoCode: '364',
    },
    {
        name: 'Iraq',
        iso2: 'IQ',
        iso3: 'IRQ',
        capital: 'Baghdad',
        region: 'AS',
        currency: {
            code: 'IQD',
            name: 'Iraqi dinar',
            symbol: 'ع.د',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+964',
        isoCode: '368',
    },
    {
        name: 'Ireland',
        iso2: 'IE',
        iso3: 'IRL',
        capital: 'Dublin',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'ga',
            name: 'Irish',
        },
        flag: '',
        numCode: '+353',
        isoCode: '372',
    },
    {
        name: 'Israel',
        iso2: 'IL',
        iso3: 'ISR',
        capital: 'Jerusalem',
        region: 'AS',
        currency: {
            code: 'ILS',
            name: 'Israeli new shekel',
            symbol: '₪',
        },
        language: {
            code: 'he',
            name: 'Hebrew (modern)',
        },
        flag: '',
        numCode: '+972',
        isoCode: '376',
    },
    {
        name: 'Italy',
        iso2: 'IT',
        iso3: 'ITA',
        capital: 'Rome',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'it',
            name: 'Italian',
        },
        flag: '',
        numCode: '+39',
        isoCode: '380',
    },
    {
        name: 'Jamaica',
        iso2: 'JM',
        iso3: 'JAM',
        capital: 'Kingston',
        region: 'NA',
        currency: {
            code: 'JMD',
            name: 'Jamaican dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '388',
    },
    {
        name: 'Japan',
        iso2: 'JP',
        iso3: 'JPN',
        capital: 'Tokyo',
        region: 'AS',
        currency: {
            code: 'JPY',
            name: 'Japanese yen',
            symbol: '¥',
        },
        language: {
            code: 'ja',
            name: 'Japanese',
        },
        flag: '',
        numCode: '+81',
        isoCode: '392',
    },
    {
        name: 'Jordan',
        iso2: 'JO',
        iso3: 'JOR',
        capital: 'Amman',
        region: 'AS',
        currency: {
            code: 'JOD',
            name: 'Jordanian dinar',
            symbol: 'د.ا',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+962',
        isoCode: '400',
    },
    {
        name: 'Kazakhstan',
        iso2: 'KZ',
        iso3: 'KAZ',
        capital: 'Astana',
        region: 'AS',
        currency: {
            code: 'KZT',
            name: 'Kazakhstani tenge',
            symbol: null,
        },
        language: {
            code: 'kk',
            name: 'Kazakh',
        },
        flag: '',
        numCode: '+7',
        isoCode: '398',
    },
    {
        name: 'Kenya',
        iso2: 'KE',
        iso3: 'KEN',
        capital: 'Nairobi',
        region: 'AF',
        currency: {
            code: 'KES',
            name: 'Kenyan shilling',
            symbol: 'Sh',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+254',
        isoCode: '404',
    },
    {
        name: 'Kiribati',
        iso2: 'KI',
        iso3: 'KIR',
        capital: 'South Tarawa',
        region: 'OC',
        currency: {
            code: 'AUD',
            name: 'Australian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+686',
        isoCode: '296',
    },
    {
        name: 'Kuwait',
        iso2: 'KW',
        iso3: 'KWT',
        capital: 'Kuwait City',
        region: 'AS',
        currency: {
            code: 'KWD',
            name: 'Kuwaiti dinar',
            symbol: 'د.ك',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+965',
        isoCode: '414',
    },
    {
        name: 'Kyrgyzstan',
        iso2: 'KG',
        iso3: 'KGZ',
        capital: 'Bishkek',
        region: 'AS',
        currency: {
            code: 'KGS',
            name: 'Kyrgyzstani som',
            symbol: 'с',
        },
        language: {
            code: 'ky',
            name: 'Kyrgyz',
        },
        flag: '',
        numCode: '+996',
        isoCode: '417',
    },
    {
        name: "Lao People's Democratic Republic",
        iso2: 'LA',
        iso3: 'LAO',
        capital: 'Vientiane',
        region: 'AS',
        currency: {
            code: 'LAK',
            name: 'Lao kip',
            symbol: '₭',
        },
        language: {
            code: 'lo',
            name: 'Lao',
        },
        flag: '',
        numCode: '+856',
        isoCode: '418',
    },
    {
        name: 'Latvia',
        iso2: 'LV',
        iso3: 'LVA',
        capital: 'Riga',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'lv',
            name: 'Latvian',
        },
        flag: '',
        numCode: '+371',
        isoCode: '428',
    },
    {
        name: 'Lebanon',
        iso2: 'LB',
        iso3: 'LBN',
        capital: 'Beirut',
        region: 'AS',
        currency: {
            code: 'LBP',
            name: 'Lebanese pound',
            symbol: 'ل.ل',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+961',
        isoCode: '422',
    },
    {
        name: 'Lesotho',
        iso2: 'LS',
        iso3: 'LSA',
        capital: 'Maseru',
        region: 'AF',
        currency: {
            code: 'LSL',
            name: 'Lesotho loti',
            symbol: 'L',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+266',
        isoCode: '426',
    },
    {
        name: 'Liberia',
        iso2: 'LR',
        iso3: 'LBR',
        capital: 'Monrovia',
        region: 'AF',
        currency: {
            code: 'LRD',
            name: 'Liberian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+231',
        isoCode: '430',
    },
    {
        name: 'Libya',
        iso2: 'LY',
        iso3: 'LBY',
        capital: 'Tripoli',
        region: 'AF',
        currency: {
            code: 'LYD',
            name: 'Libyan dinar',
            symbol: 'ل.د',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+218',
        isoCode: '434',
    },
    {
        name: 'Liechtenstein',
        iso2: 'LI',
        iso3: 'LIE',
        capital: 'Vaduz',
        region: 'EU',
        currency: {
            code: 'CHF',
            name: 'Swiss franc',
            symbol: 'Fr',
        },
        language: {
            code: 'de',
            name: 'German',
        },
        flag: '',
        numCode: '+423',
        isoCode: '438',
    },
    {
        name: 'Lithuania',
        iso2: 'LT',
        iso3: 'LTU',
        capital: 'Vilnius',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'lt',
            name: 'Lithuanian',
        },
        flag: '',
        numCode: '+370',
        isoCode: '440',
    },
    {
        name: 'Luxembourg',
        iso2: 'LU',
        iso3: 'LUX',
        capital: 'Luxembourg',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+352',
        isoCode: '442',
    },
    {
        name: 'Macao',
        iso2: 'MO',
        iso3: 'MAC',
        capital: '',
        region: 'AS',
        currency: {
            code: 'MOP',
            name: 'Macanese pataca',
            symbol: 'P',
        },
        language: {
            code: 'zh',
            name: 'Chinese',
        },
        flag: '',
        numCode: '+853',
        isoCode: '446',
    },
    {
        name: 'Macedonia (the former Yugoslav Republic of)',
        iso2: 'MK',
        iso3: 'MKD',
        capital: 'Skopje',
        region: 'EU',
        currency: {
            code: 'MKD',
            name: 'Macedonian denar',
            symbol: 'ден',
        },
        language: {
            code: 'mk',
            name: 'Macedonian',
        },
        flag: '',
        numCode: '+389',
        isoCode: '807',
    },
    {
        name: 'Madagascar',
        iso2: 'MG',
        iso3: 'MDG',
        capital: 'Antananarivo',
        region: 'AF',
        currency: {
            code: 'MGA',
            name: 'Malagasy ariary',
            symbol: 'Ar',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+261',
        isoCode: '450',
    },
    {
        name: 'Malawi',
        iso2: 'MW',
        iso3: 'MWI',
        capital: 'Lilongwe',
        region: 'AF',
        currency: {
            code: 'MWK',
            name: 'Malawian kwacha',
            symbol: 'MK',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+265',
        isoCode: '454',
    },
    {
        name: 'Malaysia',
        iso2: 'MY',
        iso3: 'MYS',
        capital: 'Kuala Lumpur',
        region: 'AS',
        currency: {
            code: 'MYR',
            name: 'Malaysian ringgit',
            symbol: 'RM',
        },
        language: {
            code: null,
            name: 'Malaysian',
        },
        flag: '',
        numCode: '+60',
        isoCode: '458',
    },
    {
        name: 'Maldives',
        iso2: 'MV',
        iso3: 'MDV',
        capital: 'Malé',
        region: 'AS',
        currency: {
            code: 'MVR',
            name: 'Maldivian rufiyaa',
            symbol: '.ރ',
        },
        language: {
            code: 'dv',
            name: 'Divehi',
        },
        flag: '',
        numCode: '+960',
        isoCode: '462',
    },
    {
        name: 'Mali',
        iso2: 'ML',
        iso3: 'MLI',
        capital: 'Bamako',
        region: 'AF',
        currency: {
            code: 'XOF',
            name: 'West African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+223',
        isoCode: '466',
    },
    {
        name: 'Malta',
        iso2: 'MT',
        iso3: 'MLT',
        capital: 'Valletta',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'mt',
            name: 'Maltese',
        },
        flag: '',
        numCode: '+356',
        isoCode: '470',
    },
    {
        name: 'Marshall Islands',
        iso2: 'MH',
        iso3: 'MHL',
        capital: 'Majuro',
        region: 'OC',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+692',
        isoCode: '584',
    },
    {
        name: 'Martinique',
        iso2: 'MQ',
        iso3: 'MTQ',
        capital: 'Fort-de-France',
        region: 'Americas',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+596',
        isoCode: '474',
    },
    {
        name: 'Mauritania',
        iso2: 'MR',
        iso3: 'MRT',
        capital: 'Nouakchott',
        region: 'AF',
        currency: {
            code: 'MRO',
            name: 'Mauritanian ouguiya',
            symbol: 'UM',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+222',
        isoCode: '478',
    },
    {
        name: 'Mauritius',
        iso2: 'MU',
        iso3: 'MUS',
        capital: 'Port Louis',
        region: 'AF',
        currency: {
            code: 'MUR',
            name: 'Mauritian rupee',
            symbol: '₨',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+230',
        isoCode: '480',
    },
    {
        name: 'Mayotte',
        iso2: 'TY',
        iso3: 'MYT',
        capital: 'Mamoudzou',
        region: 'AF',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+262',
        isoCode: '175',
    },
    {
        name: 'Mexico',
        iso2: 'MX',
        iso3: 'MEX',
        capital: 'Mexico City',
        region: 'NA',
        currency: {
            code: 'MXN',
            name: 'Mexican peso',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+52',
        isoCode: '484',
    },
    {
        name: 'Micronesia (Federated States of)',
        iso2: 'FM',
        iso3: 'FSM',
        capital: 'Palikir',
        region: 'OC',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+691',
        isoCode: '583',
    },
    {
        name: 'Moldova (Republic of)',
        iso2: 'MD',
        iso3: 'MDA',
        capital: 'Chișinău',
        region: 'EU',
        currency: {
            code: 'MDL',
            name: 'Moldovan leu',
            symbol: 'L',
        },
        language: {
            code: 'ro',
            name: 'Romanian',
        },
        flag: '',
        numCode: '+373',
        isoCode: '498',
    },
    {
        name: 'Monaco',
        iso2: 'MC',
        iso3: 'MCO',
        capital: 'Monaco',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+377',
        isoCode: '492',
    },
    {
        name: 'Mongolia',
        iso2: 'MN',
        iso3: 'MNG',
        capital: 'Ulan Bator',
        region: 'AS',
        currency: {
            code: 'MNT',
            name: 'Mongolian tögrög',
            symbol: '₮',
        },
        language: {
            code: 'mn',
            name: 'Mongolian',
        },
        flag: '',
        numCode: '+976',
        isoCode: '496',
    },
    {
        name: 'Montenegro',
        iso2: 'ME',
        iso3: 'MNE',
        capital: 'Podgorica',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'sr',
            name: 'Serbian',
        },
        flag: '',
        numCode: '+382',
        isoCode: '499',
    },
    {
        name: 'Montserrat',
        iso2: 'MS',
        iso3: 'MSR',
        capital: 'Plymouth',
        region: 'NA',
        currency: {
            code: 'XCD',
            name: 'East Caribbean dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '500',
    },
    {
        name: 'Morocco',
        iso2: 'MA',
        iso3: 'MAR',
        capital: 'Rabat',
        region: 'AF',
        currency: {
            code: 'MAD',
            name: 'Moroccan dirham',
            symbol: 'د.م.',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+212',
        isoCode: '504',
    },
    {
        name: 'Mozambique',
        iso2: 'MZ',
        iso3: 'MOZ',
        capital: 'Maputo',
        region: 'AF',
        currency: {
            code: 'MZN',
            name: 'Mozambican metical',
            symbol: 'MT',
        },
        language: {
            code: 'pt',
            name: 'Portuguese',
        },
        flag: '',
        numCode: '+258',
        isoCode: '508',
    },
    {
        name: 'Myanmar',
        iso2: 'MM',
        iso3: 'MMR',
        capital: 'Naypyidaw',
        region: 'AS',
        currency: {
            code: 'MMK',
            name: 'Burmese kyat',
            symbol: 'Ks',
        },
        language: {
            code: 'my',
            name: 'Burmese',
        },
        flag: '',
        numCode: '+95',
        isoCode: '104',
    },
    {
        name: 'Namibia',
        iso2: 'NA',
        iso3: 'NAM',
        capital: 'Windhoek',
        region: 'AF',
        currency: {
            code: 'NAD',
            name: 'Namibian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+264',
        isoCode: '516',
    },
    {
        name: 'Nauru',
        iso2: 'NR',
        iso3: 'NRU',
        capital: 'Yaren',
        region: 'OC',
        currency: {
            code: 'AUD',
            name: 'Australian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+674',
        isoCode: '520',
    },
    {
        name: 'Nepal',
        iso2: 'NP',
        iso3: 'NPL',
        capital: 'Kathmandu',
        region: 'AS',
        currency: {
            code: 'NPR',
            name: 'Nepalese rupee',
            symbol: '₨',
        },
        language: {
            code: 'ne',
            name: 'Nepali',
        },
        flag: '',
        numCode: '+977',
        isoCode: '524',
    },
    {
        name: 'Netherlands',
        iso2: 'NL',
        iso3: 'NLD',
        capital: 'Amsterdam',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'nl',
            name: 'Dutch',
        },
        flag: '',
        numCode: '+31',
        isoCode: '528',
    },
    {
        name: 'New Caledonia',
        iso2: 'NC',
        iso3: 'NCL',
        capital: 'Nouméa',
        region: 'OC',
        currency: {
            code: 'XPF',
            name: 'CFP franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+687',
        isoCode: '540',
    },
    {
        name: 'New Zealand',
        iso2: 'NZ',
        iso3: 'NZL',
        capital: 'Wellington',
        region: 'OC',
        currency: {
            code: 'NZD',
            name: 'New Zealand dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+64',
        isoCode: '554',
    },
    {
        name: 'Nicaragua',
        iso2: 'NI',
        iso3: 'NIC',
        capital: 'Managua',
        region: 'NA',
        currency: {
            code: 'NIO',
            name: 'Nicaraguan córdoba',
            symbol: 'C$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+505',
        isoCode: '558',
    },
    {
        name: 'Niger',
        iso2: 'NE',
        iso3: 'NER',
        capital: 'Niamey',
        region: 'AF',
        currency: {
            code: 'XOF',
            name: 'West African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+227',
        isoCode: '562',
    },
    {
        name: 'Nigeria',
        iso2: 'NG',
        iso3: 'NGA',
        capital: 'Abuja',
        region: 'AF',
        currency: {
            code: 'NGN',
            name: 'Nigerian naira',
            symbol: '₦',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+234',
        isoCode: '566',
    },
    {
        name: 'Niue',
        iso2: 'NU',
        iso3: 'NIU',
        capital: 'Alofi',
        region: 'OC',
        currency: {
            code: 'NZD',
            name: 'New Zealand dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+683',
        isoCode: '570',
    },
    {
        name: 'Norfolk Island',
        iso2: 'NF',
        iso3: 'NFK',
        capital: 'Kingston',
        region: 'OC',
        currency: {
            code: 'AUD',
            name: 'Australian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+672',
        isoCode: '574',
    },
    {
        name: "Korea (Democratic People's Republic of)",
        iso2: 'KP',
        iso3: 'KP',
        capital: 'Pyongyang',
        region: 'AS',
        currency: {
            code: 'KPW',
            name: 'North Korean won',
            symbol: '₩',
        },
        language: {
            code: 'ko',
            name: 'Korean',
        },
        flag: '',
        numCode: '+850',
        isoCode: '408',
    },
    {
        name: 'Northern Mariana Islands',
        iso2: 'MP',
        iso3: 'MNP',
        capital: 'Saipan',
        region: 'OC',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '580',
    },
    {
        name: 'Norway',
        iso2: 'NO',
        iso3: 'NOR',
        capital: 'Oslo',
        region: 'EU',
        currency: {
            code: 'NOK',
            name: 'Norwegian krone',
            symbol: 'kr',
        },
        language: {
            code: 'no',
            name: 'Norwegian',
        },
        flag: '',
        numCode: '+47',
        isoCode: '578',
    },
    {
        name: 'Oman',
        iso2: 'OM',
        iso3: 'OMN',
        capital: 'Muscat',
        region: 'AS',
        currency: {
            code: 'OMR',
            name: 'Omani rial',
            symbol: 'ر.ع.',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+968',
        isoCode: '512',
    },
    {
        name: 'Pakistan',
        iso2: 'PK',
        iso3: 'PAK',
        capital: 'Islamabad',
        region: 'AS',
        currency: {
            code: 'PKR',
            name: 'Pakistani rupee',
            symbol: '₨',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+92',
        isoCode: '586',
    },
    {
        name: 'Palau',
        iso2: 'PW',
        iso3: 'PLW',
        capital: 'Ngerulmud',
        region: 'OC',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+680',
        isoCode: '585',
    },
    {
        name: 'Palestine, State of',
        iso2: 'PS',
        iso3: 'PSE',
        capital: 'Ramallah',
        region: 'AS',
        currency: {
            code: 'ILS',
            name: 'Israeli new sheqel',
            symbol: '₪',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+970',
        isoCode: '275',
    },
    {
        name: 'Panama',
        iso2: 'PA',
        iso3: 'PAN',
        capital: 'Panama City',
        region: 'NA',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+507',
        isoCode: '591',
    },
    {
        name: 'Papua New Guinea',
        iso2: 'PG',
        iso3: 'PNG',
        capital: 'Port Moresby',
        region: 'OC',
        currency: {
            code: 'PGK',
            name: 'Papua New Guinean kina',
            symbol: 'K',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+675',
        isoCode: '598',
    },
    {
        name: 'Paraguay',
        iso2: 'PY',
        iso3: 'PRY',
        capital: 'Asunción',
        region: 'SA',
        currency: {
            code: 'PYG',
            name: 'Paraguayan guaraní',
            symbol: '₲',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+595',
        isoCode: '600',
    },
    {
        name: 'Peru',
        iso2: 'PE',
        iso3: 'PER',
        capital: 'Lima',
        region: 'SA',
        currency: {
            code: 'PEN',
            name: 'Peruvian sol',
            symbol: 'S/.',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+51',
        isoCode: '604',
    },
    {
        name: 'Philippines',
        iso2: 'PH',
        iso3: 'PHL',
        capital: 'Manila',
        region: 'AS',
        currency: {
            code: 'PHP',
            name: 'Philippine peso',
            symbol: '₱',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+63',
        isoCode: '608',
    },
    {
        name: 'Poland',
        iso2: 'PL',
        iso3: 'POL',
        capital: 'Warsaw',
        region: 'EU',
        currency: {
            code: 'PLN',
            name: 'Polish złoty',
            symbol: 'zł',
        },
        language: {
            code: 'pl',
            name: 'Polish',
        },
        flag: '',
        numCode: '+48',
        isoCode: '616',
    },
    {
        name: 'Portugal',
        iso2: 'PT',
        iso3: 'PRT',
        capital: 'Lisbon',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'pt',
            name: 'Portuguese',
        },
        flag: '',
        numCode: '+351',
        isoCode: '620',
    },
    {
        name: 'Puerto Rico',
        iso2: 'PR',
        iso3: 'PRI',
        capital: 'San Juan',
        region: 'NA',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+1',
        isoCode: '630',
    },
    {
        name: 'Qatar',
        iso2: 'QA',
        iso3: 'QAT',
        capital: 'Doha',
        region: 'AS',
        currency: {
            code: 'QAR',
            name: 'Qatari riyal',
            symbol: 'ر.ق',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+974',
        isoCode: '634',
    },
    {
        name: 'Republic of Kosovo',
        iso2: 'XK',
        iso3: 'XK',
        capital: 'Pristina',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'sq',
            name: 'Albanian',
        },
        flag: '',
        numCode: '+381',
        isoCode: '383',
    },
    {
        name: 'Réunion',
        iso2: 'RE',
        iso3: 'REU',
        capital: 'Saint-Denis',
        region: 'AF',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+262',
        isoCode: '638',
    },
    {
        name: 'Romania',
        iso2: 'RO',
        iso3: 'ROU',
        capital: 'Bucharest',
        region: 'EU',
        currency: {
            code: 'RON',
            name: 'Romanian leu',
            symbol: 'lei',
        },
        language: {
            code: 'ro',
            name: 'Romanian',
        },
        flag: '',
        numCode: '+40',
        isoCode: '642',
    },
    {
        name: 'Russian Federation',
        iso2: 'RU',
        iso3: 'RUS',
        capital: 'Moscow',
        region: 'EU',
        currency: {
            code: 'RUB',
            name: 'Russian ruble',
            symbol: '₽',
        },
        language: {
            code: 'ru',
            name: 'Russian',
        },
        flag: '',
        numCode: '+7',
        isoCode: '643',
    },
    {
        name: 'Rwanda',
        iso2: 'RW',
        iso3: 'RWA',
        capital: 'Kigali',
        region: 'AF',
        currency: {
            code: 'RWF',
            name: 'Rwandan franc',
            symbol: 'Fr',
        },
        language: {
            code: 'rw',
            name: 'Kinyarwanda',
        },
        flag: '',
        numCode: '+250',
        isoCode: '646',
    },
    {
        name: 'Saint Barthélemy',
        iso2: 'BL',
        iso3: 'BLM',
        capital: 'Gustavia',
        region: 'NA',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+590',
        isoCode: '652',
    },
    {
        name: 'Saint Helena, Ascension and Tristan da Cunha',
        iso2: 'SH',
        iso3: 'SHN',
        capital: 'Jamestown',
        region: 'AF',
        currency: {
            code: 'SHP',
            name: 'Saint Helena pound',
            symbol: '£',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+290',
        isoCode: '654',
    },
    {
        name: 'Saint Kitts and Nevis',
        iso2: 'KN',
        iso3: 'KNA',
        capital: 'Basseterre',
        region: 'NA',
        currency: {
            code: 'XCD',
            name: 'East Caribbean dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '659',
    },
    {
        name: 'Saint Lucia',
        iso2: 'LC',
        iso3: 'LCA',
        capital: 'Castries',
        region: 'NA',
        currency: {
            code: 'XCD',
            name: 'East Caribbean dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '662',
    },
    {
        name: 'Saint Martin (French part)',
        iso2: 'MF',
        iso3: 'MAF',
        capital: 'Marigot',
        region: 'NA',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+590',
        isoCode: '663',
    },
    {
        name: 'Saint Pierre and Miquelon',
        iso2: 'PM',
        iso3: 'SPM',
        capital: 'Saint-Pierre',
        region: 'NA',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+508',
        isoCode: '666',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        iso2: 'VC',
        iso3: 'VCT',
        capital: 'Kingstown',
        region: 'NA',
        currency: {
            code: 'XCD',
            name: 'East Caribbean dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '670',
    },
    {
        name: 'Samoa',
        iso2: 'WS',
        iso3: 'WSM',
        capital: 'Apia',
        region: 'OC',
        currency: {
            code: 'WST',
            name: 'Samoan tālā',
            symbol: 'T',
        },
        language: {
            code: 'sm',
            name: 'Samoan',
        },
        flag: '',
        numCode: '+685',
        isoCode: '882',
    },
    {
        name: 'San Marino',
        iso2: 'SM',
        iso3: 'SMR',
        capital: 'City of San Marino',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'it',
            name: 'Italian',
        },
        flag: '',
        numCode: '+378',
        isoCode: '674',
    },
    {
        name: 'Sao Tome and Principe',
        iso2: 'ST',
        iso3: 'STP',
        capital: 'São Tomé',
        region: 'AF',
        currency: {
            code: 'STD',
            name: 'São Tomé and Príncipe dobra',
            symbol: 'Db',
        },
        language: {
            code: 'pt',
            name: 'Portuguese',
        },
        flag: '',
        numCode: '+239',
        isoCode: '678',
    },
    {
        name: 'Saudi Arabia',
        iso2: 'SA',
        iso3: 'SAU',
        capital: 'Riyadh',
        region: 'AS',
        currency: {
            code: 'SAR',
            name: 'Saudi riyal',
            symbol: 'ر.س',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+966',
        isoCode: '682',
    },
    {
        name: 'Senegal',
        iso2: 'SN',
        iso3: 'SEN',
        capital: 'Dakar',
        region: 'AF',
        currency: {
            code: 'XOF',
            name: 'West African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+221',
        isoCode: '686',
    },
    {
        name: 'Serbia',
        iso2: 'RS',
        iso3: 'SRB',
        capital: 'Belgrade',
        region: 'EU',
        currency: {
            code: 'RSD',
            name: 'Serbian dinar',
            symbol: 'дин.',
        },
        language: {
            code: 'sr',
            name: 'Serbian',
        },
        flag: '',
        numCode: '+381',
        isoCode: '688',
    },
    {
        name: 'Seychelles',
        iso2: 'SC',
        iso3: 'SYC',
        capital: 'Victoria',
        region: 'AF',
        currency: {
            code: 'SCR',
            name: 'Seychellois rupee',
            symbol: '₨',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+248',
        isoCode: '690',
    },
    {
        name: 'Sierra Leone',
        iso2: 'SL',
        iso3: 'SLE',
        capital: 'Freetown',
        region: 'AF',
        currency: {
            code: 'SLL',
            name: 'Sierra Leonean leone',
            symbol: 'Le',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+232',
        isoCode: '694',
    },
    {
        name: 'Singapore',
        iso2: 'SG',
        iso3: 'SGP',
        capital: 'Singapore',
        region: 'AS',
        currency: {
            code: 'SGD',
            name: 'Singapore dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+65',
        isoCode: '702',
    },
    {
        name: 'Slovakia',
        iso2: 'SK',
        iso3: 'SVK',
        capital: 'Bratislava',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'sk',
            name: 'Slovak',
        },
        flag: '',
        numCode: '+421',
        isoCode: '703',
    },
    {
        name: 'Slovenia',
        iso2: 'SI',
        iso3: 'SVN',
        capital: 'Ljubljana',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'sl',
            name: 'Slovene',
        },
        flag: '',
        numCode: '+386',
        isoCode: '705',
    },
    {
        name: 'Solomon Islands',
        iso2: 'SB',
        iso3: 'SLB',
        capital: 'Honiara',
        region: 'OC',
        currency: {
            code: 'SBD',
            name: 'Solomon Islands dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+677',
        isoCode: '090',
    },
    {
        name: 'Somalia',
        iso2: 'SO',
        iso3: 'SOM',
        capital: 'Mogadishu',
        region: 'AF',
        currency: {
            code: 'SOS',
            name: 'Somali shilling',
            symbol: 'Sh',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+252',
        isoCode: '706',
    },
    {
        name: 'South Africa',
        iso2: 'ZA',
        iso3: 'ZAF',
        capital: 'Pretoria',
        region: 'AF',
        currency: {
            code: 'ZAR',
            name: 'South African rand',
            symbol: 'R',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+27',
        isoCode: '710',
    },
    {
        name: 'Korea (Republic of)',
        iso2: 'KR',
        iso3: 'KR',
        capital: 'Seoul',
        region: 'AS',
        currency: {
            code: 'KRW',
            name: 'South Korean won',
            symbol: '₩',
        },
        language: {
            code: 'ko',
            name: 'Korean',
        },
        flag: '',
        numCode: '+82',
        isoCode: '410',
    },
    {
        name: 'Spain',
        iso2: 'ES',
        iso3: 'ESP',
        capital: 'Madrid',
        region: 'EU',
        currency: {
            code: 'EUR',
            name: 'Euro',
            symbol: '€',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+34',
        isoCode: '724',
    },
    {
        name: 'Sri Lanka',
        iso2: 'LK',
        iso3: 'LKA',
        capital: 'Colombo',
        region: 'AS',
        currency: {
            code: 'LKR',
            name: 'Sri Lankan rupee',
            symbol: 'Rs',
        },
        language: {
            code: 'si',
            name: 'Sinhalese',
        },
        flag: '',
        numCode: '+94',
        isoCode: '144',
    },
    {
        name: 'Sudan',
        iso2: 'SD',
        iso3: 'SDN',
        capital: 'Khartoum',
        region: 'AF',
        currency: {
            code: 'SDG',
            name: 'Sudanese pound',
            symbol: 'ج.س.',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+249',
        isoCode: '729',
    },
    {
        name: 'Suriname',
        iso2: 'SR',
        iso3: 'SUR',
        capital: 'Paramaribo',
        region: 'SA',
        currency: {
            code: 'SRD',
            name: 'Surinamese dollar',
            symbol: '$',
        },
        language: {
            code: 'nl',
            name: 'Dutch',
        },
        flag: '',
        numCode: '+597',
        isoCode: '740',
    },
    {
        name: 'Swaziland',
        iso2: 'SZ',
        iso3: 'SZ',
        capital: 'Lobamba',
        region: 'AF',
        currency: {
            code: 'SZL',
            name: 'Swazi lilangeni',
            symbol: 'L',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+268',
        isoCode: '748',
    },
    {
        name: 'Sweden',
        iso2: 'SE',
        iso3: 'SWE',
        capital: 'Stockholm',
        region: 'EU',
        currency: {
            code: 'SEK',
            name: 'Swedish krona',
            symbol: 'kr',
        },
        language: {
            code: 'sv',
            name: 'Swedish',
        },
        flag: '',
        numCode: '+46',
        isoCode: '752',
    },
    {
        name: 'Switzerland',
        iso2: 'CH',
        iso3: 'CHE',
        capital: 'Bern',
        region: 'EU',
        currency: {
            code: 'CHF',
            name: 'Swiss franc',
            symbol: 'Fr',
        },
        language: {
            code: 'de',
            name: 'German',
        },
        flag: '',
        numCode: '+41',
        isoCode: '756',
    },
    {
        name: 'Syrian Arab Republic',
        iso2: 'SY',
        iso3: 'SYR',
        capital: 'Damascus',
        region: 'AS',
        currency: {
            code: 'SYP',
            name: 'Syrian pound',
            symbol: '£',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+963',
        isoCode: '760',
    },
    {
        name: 'Taiwan',
        iso2: 'TW',
        iso3: 'TWN',
        capital: 'Taipei',
        region: 'AS',
        currency: {
            code: 'TWD',
            name: 'New Taiwan dollar',
            symbol: '$',
        },
        language: {
            code: 'zh',
            name: 'Chinese',
        },
        flag: '',
        numCode: '+886',
        isoCode: '158',
    },
    {
        name: 'Tajikistan',
        iso2: 'TJ',
        iso3: 'TJK',
        capital: 'Dushanbe',
        region: 'AS',
        currency: {
            code: 'TJS',
            name: 'Tajikistani somoni',
            symbol: 'ЅМ',
        },
        language: {
            code: 'tg',
            name: 'Tajik',
        },
        flag: '',
        numCode: '+992',
        isoCode: '762',
    },
    {
        name: 'Tanzania, United Republic of',
        iso2: 'TZ',
        iso3: 'TZA',
        capital: 'Dodoma',
        region: 'AF',
        currency: {
            code: 'TZS',
            name: 'Tanzanian shilling',
            symbol: 'Sh',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+255',
        isoCode: '834',
    },
    {
        name: 'Thailand',
        iso2: 'TH',
        iso3: 'THA',
        capital: 'Bangkok',
        region: 'AS',
        currency: {
            code: 'THB',
            name: 'Thai baht',
            symbol: '฿',
        },
        language: {
            code: 'th',
            name: 'Thai',
        },
        flag: '',
        numCode: '+66',
        isoCode: '764',
    },
    {
        name: 'Timor-Leste',
        iso2: 'TL',
        iso3: 'TLS',
        capital: 'Dili',
        region: 'AS',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'pt',
            name: 'Portuguese',
        },
        flag: '',
        numCode: '+670',
        isoCode: '626',
    },
    {
        name: 'Togo',
        iso2: 'TG',
        iso3: 'TGO',
        capital: 'Lomé',
        region: 'AF',
        currency: {
            code: 'XOF',
            name: 'West African CFA franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+228',
        isoCode: '768',
    },
    {
        name: 'Tokelau',
        iso2: 'TK',
        iso3: 'TKL',
        capital: 'Fakaofo',
        region: 'OC',
        currency: {
            code: 'NZD',
            name: 'New Zealand dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+690',
        isoCode: '772',
    },
    {
        name: 'Tonga',
        iso2: 'TO',
        iso3: 'TON',
        capital: "Nuku'alofa",
        region: 'OC',
        currency: {
            code: 'TOP',
            name: 'Tongan paʻanga',
            symbol: 'T$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+676',
        isoCode: '776',
    },
    {
        name: 'Trinidad and Tobago',
        iso2: 'TT',
        iso3: 'TTO',
        capital: 'Port of Spain',
        region: 'SA',
        currency: {
            code: 'TTD',
            name: 'Trinidad and Tobago dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '780',
    },
    {
        name: 'Tunisia',
        iso2: 'TN',
        iso3: 'TUN',
        capital: 'Tunis',
        region: 'AF',
        currency: {
            code: 'TND',
            name: 'Tunisian dinar',
            symbol: 'د.ت',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+216',
        isoCode: '788',
    },
    {
        name: 'Turkey',
        iso2: 'TR',
        iso3: 'TUR',
        capital: 'Ankara',
        region: 'AS',
        currency: {
            code: 'TRY',
            name: 'Turkish lira',
            symbol: null,
        },
        language: {
            code: 'tr',
            name: 'Turkish',
        },
        flag: '',
        numCode: '+90',
        isoCode: '792',
    },
    {
        name: 'Turkmenistan',
        iso2: 'TM',
        iso3: 'TKM',
        capital: 'Ashgabat',
        region: 'AS',
        currency: {
            code: 'TMT',
            name: 'Turkmenistan manat',
            symbol: 'm',
        },
        language: {
            code: 'tk',
            name: 'Turkmen',
        },
        flag: '',
        numCode: '+993',
        isoCode: '795',
    },
    {
        name: 'Turks and Caicos Islands',
        iso2: 'TC',
        iso3: 'TCA',
        capital: 'Cockburn Town',
        region: 'NA',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '796',
    },
    {
        name: 'Tuvalu',
        iso2: 'TV',
        iso3: 'TUV',
        capital: 'Funafuti',
        region: 'OC',
        currency: {
            code: 'AUD',
            name: 'Australian dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+688',
        isoCode: '798',
    },
    {
        name: 'Uganda',
        iso2: 'UG',
        iso3: 'UGA',
        capital: 'Kampala',
        region: 'AF',
        currency: {
            code: 'UGX',
            name: 'Ugandan shilling',
            symbol: 'Sh',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+256',
        isoCode: '800',
    },
    {
        name: 'Ukraine',
        iso2: 'UA',
        iso3: 'UKR',
        capital: 'Kiev',
        region: 'EU',
        currency: {
            code: 'UAH',
            name: 'Ukrainian hryvnia',
            symbol: '₴',
        },
        language: {
            code: 'uk',
            name: 'Ukrainian',
        },
        flag: '',
        numCode: '+380',
        isoCode: '804',
    },
    {
        name: 'United Arab Emirates',
        iso2: 'AE',
        iso3: 'ARE',
        capital: 'Abu Dhabi',
        region: 'AS',
        currency: {
            code: 'AED',
            name: 'United Arab Emirates dirham',
            symbol: 'د.إ',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+971',
        isoCode: '784',
    },
    {
        name: 'United Kingdom of Great Britain and Northern Ireland',
        iso2: 'GB',
        iso3: 'GBR',
        capital: 'London',
        region: 'EU',
        currency: {
            code: 'GBP',
            name: 'British pound',
            symbol: '£',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+44',
        isoCode: '826',
    },
    {
        name: 'United States of America',
        iso2: 'US',
        iso3: 'USA',
        capital: 'Washington, D.C.',
        region: 'NA',
        currency: {
            code: 'USD',
            name: 'United States dollar',
            symbol: '$',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+1',
        isoCode: '840',
    },
    {
        name: 'Uruguay',
        iso2: 'UY',
        iso3: 'URY',
        capital: 'Montevideo',
        region: 'SA',
        currency: {
            code: 'UYU',
            name: 'Uruguayan peso',
            symbol: '$',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+598',
        isoCode: '858',
    },
    {
        name: 'Uzbekistan',
        iso2: 'UZ',
        iso3: 'UZB',
        capital: 'Tashkent',
        region: 'AS',
        currency: {
            code: 'UZS',
            name: "Uzbekistani so'm",
            symbol: null,
        },
        language: {
            code: 'uz',
            name: 'Uzbek',
        },
        flag: '',
        numCode: '+998',
        isoCode: '860',
    },
    {
        name: 'Vanuatu',
        iso2: 'VU',
        iso3: 'VUT',
        capital: 'Port Vila',
        region: 'OC',
        currency: {
            code: 'VUV',
            name: 'Vanuatu vatu',
            symbol: 'Vt',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+678',
        isoCode: '548',
    },
    {
        name: 'Venezuela (Bolivarian Republic of)',
        iso2: 'VE',
        iso3: 'VEN',
        capital: 'Caracas',
        region: 'SA',
        currency: {
            code: 'VEF',
            name: 'Venezuelan bolívar',
            symbol: 'Bs F',
        },
        language: {
            code: 'es',
            name: 'Spanish',
        },
        flag: '',
        numCode: '+58',
        isoCode: '862',
    },
    {
        name: 'Viet Nam',
        iso2: 'VN',
        iso3: 'VNM',
        capital: 'Hanoi',
        region: 'AS',
        currency: {
            code: 'VND',
            name: 'Vietnamese đồng',
            symbol: '₫',
        },
        language: {
            code: 'vi',
            name: 'Vietnamese',
        },
        flag: '',
        numCode: '+84',
        isoCode: '704',
    },
    {
        name: 'Wallis and Futuna',
        iso2: 'WF',
        iso3: 'WLF',
        capital: 'Mata-Utu',
        region: 'OC',
        currency: {
            code: 'XPF',
            name: 'CFP franc',
            symbol: 'Fr',
        },
        language: {
            code: 'fr',
            name: 'French',
        },
        flag: '',
        numCode: '+681',
        isoCode: '876',
    },
    {
        name: 'Yemen',
        iso2: 'YE',
        iso3: 'YEM',
        capital: "Sana'a",
        region: 'AS',
        currency: {
            code: 'YER',
            name: 'Yemeni rial',
            symbol: '﷼',
        },
        language: {
            code: 'ar',
            name: 'Arabic',
        },
        flag: '',
        numCode: '+967',
        isoCode: '887',
    },
    {
        name: 'Zambia',
        iso2: 'ZM',
        iso3: 'ZMB',
        capital: 'Lusaka',
        region: 'AF',
        currency: {
            code: 'ZMW',
            name: 'Zambian kwacha',
            symbol: 'ZK',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+260',
        isoCode: '894',
    },
    {
        name: 'Zimbabwe',
        iso2: 'ZW',
        iso3: 'ZWE',
        capital: 'Harare',
        region: 'AF',
        currency: {
            code: 'BWP',
            name: 'Botswana pula',
            symbol: 'P',
        },
        language: {
            code: 'en',
            name: 'English',
        },
        flag: '',
        numCode: '+263',
        isoCode: '716',
    },
];

// adaptor function convert to string
const convertObjToString = () => {
    return countriesRawData.map((country) => {
        const { currency, language, ...rest } = country;
        return {
            ...rest,
            currency: JSON.stringify(currency),
            language: JSON.stringify(language),
        };
    });
};
export const CountriesAndCodes = convertObjToString();
